# Generated by Django 5.1.6 on 2025-02-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='razorpay_signature',
        ),
    ]
