# Generated by Django 5.1.6 on 2025-02-18 08:10

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], db_index=True, max_length=10)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], db_index=True, max_length=10)),
                ('collection_date', models.DateField(db_index=True)),
                ('base_fat_percentage', models.DecimalField(decimal_places=2, default=6.5, max_digits=4)),
                ('base_snf_percentage', models.DecimalField(decimal_places=2, default=9.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('9.0'), message='Base SNF percentage cannot be less than 9.0'), django.core.validators.MaxValueValidator(Decimal('9.5'), message='Base SNF percentage cannot be more than 9.5')])),
                ('measured', models.CharField(choices=[('liters', 'Liters'), ('kg', 'Kg')], max_length=10)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('snf_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=50)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=100)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DairyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dairy_name', models.CharField(db_index=True, max_length=255)),
                ('dairy_address', models.TextField(blank=True)),
                ('rate_type', models.CharField(choices=[('fat_only', 'Fat Only'), ('fat_snf', 'Fat + SNF'), ('fat_clr', 'Fat + CLR')], db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Dairy Information',
                'verbose_name_plural': 'Dairy Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketMilkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=100)),
            ],
        ),
    ]
