# Generated by Django 5.1.6 on 2025-02-14 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_marketmilkprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='fat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='snf_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.CreateModel(
            name='RateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('rate per kg', 'Rate per kg')], max_length=50)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10)),
                ('fat_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('snf_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RateChart',
        ),
    ]
