# Generated by Django 5.1.6 on 2025-02-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_collection_fat_rate_alter_collection_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy_name', models.CharField(max_length=255)),
                ('dairy_address', models.TextField(blank=True)),
                ('rate_type', models.CharField(choices=[('fat_only', 'Fat Only'), ('fat_snf', 'Fat + SNF'), ('fat_clr', 'Fat + CLR')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dairy Information',
                'verbose_name_plural': 'Dairy Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
